//Categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_ERROR'

//All products
export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST'
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS'
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE'

//Category products
export const FETCH_CATEGORY_PRODUCTS_REQUEST = 'FETCH_CATEGORY_PRODUCT_REQUEST'
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = 'FETCH_CATEGORY_PRODUCT_SUCCESS'
export const FETCH_CATEGORY_PRODUCTS_FAILURE = 'FETCH_CATEGORY_PRODUCT_FAILURE'

//SubProducts
export const FETCH_SUB_PRODUCTS_REQUEST = 'FETCH_SUB_PRODUCTS_REQUEST'
export const FETCH_SUB_PRODUCTS_SUCCESS = 'FETCH_SUB_PRODUCTS_SUCCESS'
export const FETCH_SUB_PRODUCTS_FAILURE = 'FETCH_SUB_PRODUCTS_FAILURE'

//Cart Items
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const UPDATE_CART_UNITS = 'UPDATE_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
